name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 先安装基础科学计算库（避免依赖冲突）
        pip install wheel setuptools
        pip install numpy==1.24.3
        pip install pandas==2.1.1
        # 安装其他依赖
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Verify project structure
      run: |
        echo "项目文件结构:"
        dir
        echo "静态文件:"
        dir static
        echo "模板文件:"
        dir templates
        
    - name: Build executable
      run: |
        echo "开始构建Windows可执行文件..."
        echo "Python版本信息:"
        python --version
        echo "当前工作目录:"
        pwd
        echo "检查spec文件:"
        type stock_analyzer.spec
        echo "检查launcher.py:"
        type launcher.py
        echo "开始PyInstaller构建..."
        pyinstaller --clean --log-level=DEBUG stock_analyzer.spec
        
    - name: Check build output
      run: |
        echo "构建结果:"
        dir dist
        echo "文件大小:"
        powershell "Get-ChildItem dist\StockAnalyzer.exe | Select-Object Name, @{Name='Size(MB)';Expression={[math]::Round($_.Length/1MB, 2)}}"
        
    - name: Create release package
      run: |
        # 创建发布包
        mkdir release
        copy dist\StockAnalyzer.exe release\
        copy README_WINDOWS_BUILD.md release\README.md
        echo "# 股票分析系统 Windows 版本" > release\使用说明.txt
        echo "" >> release\使用说明.txt
        echo "1. 双击 StockAnalyzer.exe 启动程序" >> release\使用说明.txt
        echo "2. 程序会自动打开浏览器访问 http://localhost:5001" >> release\使用说明.txt
        echo "3. 如果浏览器没有自动打开，请手动访问上述地址" >> release\使用说明.txt
        echo "4. 关闭控制台窗口即可停止程序" >> release\使用说明.txt
        echo "" >> release\使用说明.txt
        echo "系统要求：Windows 7/8/10/11 (64-bit)" >> release\使用说明.txt
        echo "网络要求：需要联网获取实时股票数据" >> release\使用说明.txt
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: StockAnalyzer-Windows-${{ github.sha }}
        path: release/
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/StockAnalyzer.exe
          release/README.md
          release/使用说明.txt
        name: 股票分析系统 ${{ github.ref_name }}
        body: |
          ## 股票分析系统 Windows 版本
          
          ### 功能特点
          - 上证A股实时行情查看
          - 技术分析图表（K线图、趋势分析）
          - 基本面分析（财务指标、资产负债表等）
          - 大盘分析（上证指数历史数据）
          - 行业分析和股票筛选
          
          ### 使用方法
          1. 下载 `StockAnalyzer.exe`
          2. 双击运行（首次启动可能需要10-20秒）
          3. 自动打开浏览器访问系统界面
          
          ### 系统要求
          - Windows 7/8/10/11 (64-bit)
          - 需要联网获取实时数据
          
          ### 文件说明
          - `StockAnalyzer.exe`: 主程序（~200-300MB）
          - `README.md`: 详细使用说明
          - `使用说明.txt`: 快速上手指南
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}